/*
 * generated by Xtext
 */
package org.mda.editor.xtext;

import org.eclipse.xtext.resource.XtextResource;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MidiPlayerRuntimeModule extends org.mda.editor.xtext.AbstractMidiPlayerRuntimeModule {

  public Class<? extends XtextResource> bindXtextResource() {
    return InMemoryXtextResource.class;
  }

}
