/*
* generated by Xtext
*/
package org.mda.editor.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MidiPlayerOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
