/*
* generated by Xtext
*/
package org.mda.editor.xtext.ui.contentassist;

import org.mda.editor.xtext.ui.contentassist.AbstractMidiPlayerProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MidiPlayerProposalProvider extends AbstractMidiPlayerProposalProvider {

}
