/*
 * generated by Xtext
 */
package org.mda.editor.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MidiPlayerUiModule extends org.mda.editor.xtext.ui.AbstractMidiPlayerUiModule {
	public MidiPlayerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}


}
